from sqlalchemy.ext.asyncio import AsyncSession

from app.llms.base import BaseLLMClient
from app.schemas.model import ModelInfo
from app.db.models import Critique, Prompt

CRITIC_SYSTEM_PROMPT = """
You are an expert evaluator of AI prompts.

Evaluate the given prompt and respond STRICTLY in JSON with:
- score (float 0–10)
- strengths (list of strings)
- weaknesses (list of strings)
- suggestions (list of strings)
- tone (one of: polite, neutral, brutal)
"""

import json


class CriticEngine:
    """
    Responsible for evaluating prompts generated by creators.
    """

    def __init__(self, llm_client: BaseLLMClient):
        self.llm = llm_client

    async def critique_prompt(
        self,
        *,
        db: AsyncSession,
        prompt: Prompt,
        critic_model: ModelInfo,
        temperature: float,
        max_tokens: int,
        seed: int,
        source_visible: bool,
    ) -> Critique:

        if source_visible:
            source_info = (
                f"This prompt was generated by model "
                f"{prompt.creator_provider}/{prompt.creator_model}."
            )
        else:
            source_info = "The source model of this prompt is unknown."

        messages = [
            {"role": "system", "content": CRITIC_SYSTEM_PROMPT},
            {
                "role": "user",
                "content": f"{source_info}\n\nPROMPT:\n{prompt.content}",
            },
        ]

        response = await self.llm.generate(
            messages=messages,
            model=critic_model.full_id(),
            temperature=temperature,
            max_tokens=max_tokens,
            seed=seed,
        )

        # Parse structured output
        try:
            parsed = json.loads(response["content"])
        except json.JSONDecodeError:
            # fallback for mock or malformed outputs
            parsed = {
                "score": 0.0,
                "strengths": [],
                "weaknesses": [],
                "suggestions": [],
                "tone": None,
            }


        critique = Critique(
            prompt_id=str(prompt.id),
            critic_provider=critic_model.provider,
            critic_model=critic_model.model_name,
            critic_version=critic_model.version,
            source_visible=source_visible,
            score=float(parsed["score"]),
            strengths=parsed["strengths"],
            weaknesses=parsed["weaknesses"],
            suggestions=parsed["suggestions"],
            tone=parsed.get("tone"),
            raw_text=response["content"],
        )

        db.add(critique)
        await db.commit()
        await db.refresh(critique)

        return critique
